[book]
authors = ["pblottiere"]
language = "en"
multilingual = false
src = "src"
title = "PharoOWS Documentation"

[build]
build-dir = "./build"

[output.html]
curly-quotes = true
additional-css = ["custom.css"]
git-repository-url = "https://github.com/ThalesGroup/PharoOWS"
