name: 'CI'

on:
  pull_request: #necessary to display "check" step in a PR
    types: [labeled]
  workflow_dispatch: #manual trigger

jobs:
  test:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.label.name == 'run-ci')
    strategy:
      # Default value means that a failure in one OS cancels all 
      fail-fast: false
      matrix:
        smalltalk: [ Pharo64-11, Pharo64-12, Pharo64-13 ]
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.smalltalk }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup smalltalkCI
        uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Load in New Image and Run Tests
        run: smalltalkci -s ${{ matrix.smalltalk }} .smalltalkci.default.ston
        shell: bash
        timeout-minutes: 10
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: Logs_${{ matrix.smalltalk }}_${{ matrix.os }}
          path: |
            *.fuel
            PharoDebug.log
          retention-days: 3